version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

  content-generation:
    build:
      context: .
      dockerfile: apps/content-generation/Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - mongo
    networks:
      - app-network

  content-management:
    build:
      context: .
      dockerfile: apps/content-management/Dockerfile
    ports:
      - "3334:3334"
    depends_on:
      - mongo
    networks:
      - app-network

  user-sub-management:
    build:
      context: .
      dockerfile: apps/user-sub-management/Dockerfile
    ports:
      - "3335:3335"
    depends_on:
      - mongo
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - content-generation
      - content-management
      - user-sub-management
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
